/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace/index'
import { Route as AuthenticatedFarmerIndexRouteImport } from './routes/_authenticated/farmer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMarketplaceIdRouteImport } from './routes/_authenticated/marketplace/$id'
import { Route as AuthenticatedFarmerFeedPurchaseRouteImport } from './routes/_authenticated/farmer/feed-purchase'
import { Route as AuthenticatedFarmerChicksPurchaseRouteImport } from './routes/_authenticated/farmer/chicks-purchase'
import { Route as AuthenticatedFarmerBirdsSellRouteImport } from './routes/_authenticated/farmer/birds-sell'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminManageListingsRouteImport } from './routes/_authenticated/admin.manage-listings'
import { Route as AuthenticatedAdminFeedSellRouteImport } from './routes/_authenticated/admin.feed-sell'
import { Route as AuthenticatedAdminChicksSellRouteImport } from './routes/_authenticated/admin.chicks-sell'
import { Route as AuthenticatedFarmerListingsNewRouteImport } from './routes/_authenticated/farmer/listings/new'
import { Route as AuthenticatedFarmerListingsIdEditRouteImport } from './routes/_authenticated/farmer/listings/$id/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerIndexRoute =
  AuthenticatedFarmerIndexRouteImport.update({
    id: '/farmer/',
    path: '/farmer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMarketplaceIdRoute =
  AuthenticatedMarketplaceIdRouteImport.update({
    id: '/marketplace/$id',
    path: '/marketplace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerFeedPurchaseRoute =
  AuthenticatedFarmerFeedPurchaseRouteImport.update({
    id: '/farmer/feed-purchase',
    path: '/farmer/feed-purchase',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerChicksPurchaseRoute =
  AuthenticatedFarmerChicksPurchaseRouteImport.update({
    id: '/farmer/chicks-purchase',
    path: '/farmer/chicks-purchase',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerBirdsSellRoute =
  AuthenticatedFarmerBirdsSellRouteImport.update({
    id: '/farmer/birds-sell',
    path: '/farmer/birds-sell',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManageListingsRoute =
  AuthenticatedAdminManageListingsRouteImport.update({
    id: '/manage-listings',
    path: '/manage-listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedSellRoute =
  AuthenticatedAdminFeedSellRouteImport.update({
    id: '/feed-sell',
    path: '/feed-sell',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChicksSellRoute =
  AuthenticatedAdminChicksSellRouteImport.update({
    id: '/chicks-sell',
    path: '/chicks-sell',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedFarmerListingsNewRoute =
  AuthenticatedFarmerListingsNewRouteImport.update({
    id: '/farmer/listings/new',
    path: '/farmer/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerListingsIdEditRoute =
  AuthenticatedFarmerListingsIdEditRouteImport.update({
    id: '/farmer/listings/$id/edit',
    path: '/farmer/listings/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/chicks-sell': typeof AuthenticatedAdminChicksSellRoute
  '/admin/feed-sell': typeof AuthenticatedAdminFeedSellRoute
  '/admin/manage-listings': typeof AuthenticatedAdminManageListingsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/farmer/birds-sell': typeof AuthenticatedFarmerBirdsSellRoute
  '/farmer/chicks-purchase': typeof AuthenticatedFarmerChicksPurchaseRoute
  '/farmer/feed-purchase': typeof AuthenticatedFarmerFeedPurchaseRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/farmer/': typeof AuthenticatedFarmerIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/farmer/listings/new': typeof AuthenticatedFarmerListingsNewRoute
  '/farmer/listings/$id/edit': typeof AuthenticatedFarmerListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/admin/chicks-sell': typeof AuthenticatedAdminChicksSellRoute
  '/admin/feed-sell': typeof AuthenticatedAdminFeedSellRoute
  '/admin/manage-listings': typeof AuthenticatedAdminManageListingsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/farmer/birds-sell': typeof AuthenticatedFarmerBirdsSellRoute
  '/farmer/chicks-purchase': typeof AuthenticatedFarmerChicksPurchaseRoute
  '/farmer/feed-purchase': typeof AuthenticatedFarmerFeedPurchaseRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/farmer': typeof AuthenticatedFarmerIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/farmer/listings/new': typeof AuthenticatedFarmerListingsNewRoute
  '/farmer/listings/$id/edit': typeof AuthenticatedFarmerListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/admin/chicks-sell': typeof AuthenticatedAdminChicksSellRoute
  '/_authenticated/admin/feed-sell': typeof AuthenticatedAdminFeedSellRoute
  '/_authenticated/admin/manage-listings': typeof AuthenticatedAdminManageListingsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/farmer/birds-sell': typeof AuthenticatedFarmerBirdsSellRoute
  '/_authenticated/farmer/chicks-purchase': typeof AuthenticatedFarmerChicksPurchaseRoute
  '/_authenticated/farmer/feed-purchase': typeof AuthenticatedFarmerFeedPurchaseRoute
  '/_authenticated/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/farmer/': typeof AuthenticatedFarmerIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/farmer/listings/new': typeof AuthenticatedFarmerListingsNewRoute
  '/_authenticated/farmer/listings/$id/edit': typeof AuthenticatedFarmerListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/pending'
    | '/admin/chicks-sell'
    | '/admin/feed-sell'
    | '/admin/manage-listings'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/farmer/birds-sell'
    | '/farmer/chicks-purchase'
    | '/farmer/feed-purchase'
    | '/marketplace/$id'
    | '/admin/'
    | '/farmer/'
    | '/marketplace/'
    | '/farmer/listings/new'
    | '/farmer/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/pending'
    | '/admin/chicks-sell'
    | '/admin/feed-sell'
    | '/admin/manage-listings'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/farmer/birds-sell'
    | '/farmer/chicks-purchase'
    | '/farmer/feed-purchase'
    | '/marketplace/$id'
    | '/admin'
    | '/farmer'
    | '/marketplace'
    | '/farmer/listings/new'
    | '/farmer/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/pending'
    | '/_authenticated/admin/chicks-sell'
    | '/_authenticated/admin/feed-sell'
    | '/_authenticated/admin/manage-listings'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/farmer/birds-sell'
    | '/_authenticated/farmer/chicks-purchase'
    | '/_authenticated/farmer/feed-purchase'
    | '/_authenticated/marketplace/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/farmer/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/farmer/listings/new'
    | '/_authenticated/farmer/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer/': {
      id: '/_authenticated/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof AuthenticatedFarmerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/marketplace/$id': {
      id: '/_authenticated/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer/feed-purchase': {
      id: '/_authenticated/farmer/feed-purchase'
      path: '/farmer/feed-purchase'
      fullPath: '/farmer/feed-purchase'
      preLoaderRoute: typeof AuthenticatedFarmerFeedPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer/chicks-purchase': {
      id: '/_authenticated/farmer/chicks-purchase'
      path: '/farmer/chicks-purchase'
      fullPath: '/farmer/chicks-purchase'
      preLoaderRoute: typeof AuthenticatedFarmerChicksPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer/birds-sell': {
      id: '/_authenticated/farmer/birds-sell'
      path: '/farmer/birds-sell'
      fullPath: '/farmer/birds-sell'
      preLoaderRoute: typeof AuthenticatedFarmerBirdsSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manage-listings': {
      id: '/_authenticated/admin/manage-listings'
      path: '/manage-listings'
      fullPath: '/admin/manage-listings'
      preLoaderRoute: typeof AuthenticatedAdminManageListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feed-sell': {
      id: '/_authenticated/admin/feed-sell'
      path: '/feed-sell'
      fullPath: '/admin/feed-sell'
      preLoaderRoute: typeof AuthenticatedAdminFeedSellRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chicks-sell': {
      id: '/_authenticated/admin/chicks-sell'
      path: '/chicks-sell'
      fullPath: '/admin/chicks-sell'
      preLoaderRoute: typeof AuthenticatedAdminChicksSellRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/farmer/listings/new': {
      id: '/_authenticated/farmer/listings/new'
      path: '/farmer/listings/new'
      fullPath: '/farmer/listings/new'
      preLoaderRoute: typeof AuthenticatedFarmerListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer/listings/$id/edit': {
      id: '/_authenticated/farmer/listings/$id/edit'
      path: '/farmer/listings/$id/edit'
      fullPath: '/farmer/listings/$id/edit'
      preLoaderRoute: typeof AuthenticatedFarmerListingsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminChicksSellRoute: typeof AuthenticatedAdminChicksSellRoute
  AuthenticatedAdminFeedSellRoute: typeof AuthenticatedAdminFeedSellRoute
  AuthenticatedAdminManageListingsRoute: typeof AuthenticatedAdminManageListingsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminChicksSellRoute: AuthenticatedAdminChicksSellRoute,
  AuthenticatedAdminFeedSellRoute: AuthenticatedAdminFeedSellRoute,
  AuthenticatedAdminManageListingsRoute: AuthenticatedAdminManageListingsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedFarmerBirdsSellRoute: typeof AuthenticatedFarmerBirdsSellRoute
  AuthenticatedFarmerChicksPurchaseRoute: typeof AuthenticatedFarmerChicksPurchaseRoute
  AuthenticatedFarmerFeedPurchaseRoute: typeof AuthenticatedFarmerFeedPurchaseRoute
  AuthenticatedMarketplaceIdRoute: typeof AuthenticatedMarketplaceIdRoute
  AuthenticatedFarmerIndexRoute: typeof AuthenticatedFarmerIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedFarmerListingsNewRoute: typeof AuthenticatedFarmerListingsNewRoute
  AuthenticatedFarmerListingsIdEditRoute: typeof AuthenticatedFarmerListingsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedFarmerBirdsSellRoute: AuthenticatedFarmerBirdsSellRoute,
  AuthenticatedFarmerChicksPurchaseRoute:
    AuthenticatedFarmerChicksPurchaseRoute,
  AuthenticatedFarmerFeedPurchaseRoute: AuthenticatedFarmerFeedPurchaseRoute,
  AuthenticatedMarketplaceIdRoute: AuthenticatedMarketplaceIdRoute,
  AuthenticatedFarmerIndexRoute: AuthenticatedFarmerIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedFarmerListingsNewRoute: AuthenticatedFarmerListingsNewRoute,
  AuthenticatedFarmerListingsIdEditRoute:
    AuthenticatedFarmerListingsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
